appName: api-gateway
autoscaling:
  enabled: false
  maxReplicas: 10
  minReplicas: 2
  scaleDownStabilization: 300
  scaleUpStabilization: 0
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
config:
  logLevel: INFO
containerPort: 8080
environment: local
image:
  pullPolicy: IfNotPresent
  repository: registry.tradefence.in:5000/api-gateway
  tag: 1.0.0.alpha.3-build.20260127-0151.3006f73
ingress:
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: 'true'
    traefik.ingress.kubernetes.io/service.sticky.cookie.httponly: 'true'
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: gateway-session
    traefik.ingress.kubernetes.io/service.sticky.cookie.samesite: strict
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: 'true'
  enabled: true
  hosts:
  - host: api.local.tradefence.in
    paths:
    - path: /
      pathType: Prefix
  ingressClassName: traefik
  tls:
  - hosts:
    - api.local.tradefence.in
    secretName: api-local-tradefence-tls
internalServices:
  logEndpoint: http://loki-write.monitoring.svc.cluster.local:3100/loki/api/v1/push
  telemetryEndpoint: tempo.monitoring:4317
  userServiceGRPC: user-service:9090
linkerd:
  inject: true
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 30
  path: /health
  periodSeconds: 10
  timeoutSeconds: 5
namespace: app
podDisruptionBudget:
  enabled: false
  minAvailable: 1
rateLimiter:
  burst: 5
  enabled: true
  rps: 1
  type: pod_ip
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  path: /ready
  periodSeconds: 5
  timeoutSeconds: 3
replicaCount: 2
resources:
  limits:
    cpu: 1000m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
revisionHistoryLimit: 0
service:
  port: 8080
  targetPort: 8080
  type: ClusterIP
version: 1.0.0.alpha.3-build.20260127-0151.3006f73
