apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
  annotations:
    config.linkerd.io/opaque-ports: "4222,6222,8222"
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: {{ .Values.appName }}
  ports:
  - name: nats-client
    port: {{ .Values.ports.client }}
    targetPort: nats-client
    protocol: TCP
  - name: nats-cluster
    port: {{ .Values.ports.cluster }}
    targetPort: nats-cluster
    protocol: TCP
  - name: nats-monitoring
    port: {{ .Values.ports.monitoring }}
    targetPort: nats-monitoring
    protocol: TCP
