apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Values.namespace }}
data:

  # Application configuration
  LOG_LEVEL: "{{ .Values.config.logLevel }}"

  # Rate limiter configuration
  RATE_LIMITER_ENABLED: "{{ .Values.rateLimiter.enabled }}"
  RATE_LIMITER_TYPE: "{{ .Values.rateLimiter.type }}"
  RATE_LIMITER_BURST: "{{ .Values.rateLimiter.burst }}"
  RATE_LIMITER_RPS: "{{ .Values.rateLimiter.rps }}"

  USER_SERVICE_GRPC: "{{ .Values.internalServices.userServiceGRPC }}"
  TELEMETRY_ENDPOINT: "{{ .Values.internalServices.telemetryEndpoint }}"
  LOG_ENDPOINT: "{{ .Values.internalServices.logEndpoint }}"

  {{- range $key, $value := .Values.config.custom }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
