apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
data:

  # Monitoring configuration
  LOG_LEVEL: "{{ .Values.config.logLevel }}"
  TELEMETRY_ENDPOINT: "{{ .Values.config.internalServices.telemetryEndpoint }}"

  # Rate limiter configuration
  RATE_LIMITER_ENABLED: "{{ .Values.config.rateLimiter.enabled }}"
  RATE_LIMITER_TYPE: "{{ .Values.config.rateLimiter.type }}"
  RATE_LIMITER_BURST: "{{ .Values.config.rateLimiter.burst }}"
  RATE_LIMITER_RPS: "{{ .Values.config.rateLimiter.rps }}"

  # Internal services configuration
  USER_SERVICE_GRPC: "{{ .Values.config.internalServices.userServiceGRPC }}"

  {{- range $key, $value := .Values.config.custom }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
