apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Values.namespace }}
data:

  REDIS_HOST: "{{ .Values.redis.host }}"
  REDIS_PORT: "{{ .Values.redis.port }}"
  REDIS_MAX_CONNECTIONS: "{{ .Values.redis.maxConnections }}"
  REDIS_TIMEOUT: "{{ .Values.redis.timeout }}"

  # gRPC client configuration
  GRPC_KEEPALIVE_TIME: "{{ .Values.grpc.keepaliveTime }}"
  GRPC_KEEPALIVE_TIMEOUT: "{{ .Values.grpc.keepaliveTimeout }}"
  GRPC_PERMIT_WITHOUT_STREAM: "{{ .Values.grpc.permitWithoutStream }}"
  GRPC_MAX_CONNECTION_IDLE: "{{ .Values.grpc.maxConnectionIdle }}"
  GRPC_MAX_CONNECTION_AGE: "{{ .Values.grpc.maxConnectionAge }}"

  # Auth configuration
  AUTH_TOKEN_EXPIRY: "{{ .Values.auth.tokenExpiry }}"

  # Application configuration
  LOG_LEVEL: "{{ .Values.config.logLevel }}"
  WEBSOCKET_READ_BUFFER_SIZE: "{{ .Values.config.websocketReadBufferSize }}"
  WEBSOCKET_WRITE_BUFFER_SIZE: "{{ .Values.config.websocketWriteBufferSize }}"
  WEBSOCKET_MAX_MESSAGE_SIZE: "{{ .Values.config.websocketMaxMessageSize }}"

  # Rate limiter configuration
  RATE_LIMITER_ENABLED: "{{ .Values.rateLimiter.enabled }}"
  RATE_LIMITER_TYPE: "{{ .Values.rateLimiter.type }}"
  RATE_LIMITER_BURST: "{{ .Values.rateLimiter.burst }}"
  RATE_LIMITER_RPS: "{{ .Values.rateLimiter.rps }}"

  USER_DATA_SERVICE_URL: "{{ .Values.internalServices.userService }}"

  # etcd configuration
  ETCD_ENDPOINTS: "{{ .Values.etcd.endpoints | join "," }}"

  {{- range $key, $value := .Values.config.custom }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
