apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ws-gateway.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ws-gateway.labels" . | nindent 4 }}
