apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Values.namespace }}
data:

  REDIS_HOST: "{{ .Values.redis.host }}"
  REDIS_PORT: "{{ .Values.redis.port }}"
  REDIS_MAX_CONNECTIONS: "{{ .Values.redis.maxConnections }}"
  REDIS_TIMEOUT: "{{ .Values.redis.timeout }}"

  # Application configuration
  LOG_LEVEL: "{{ .Values.config.logLevel }}"

  # Database configuration
  DATABASE_POSTGRES_1: "{{ .Values.database.postgres_1 }}"

  # etcd configuration
  ETCD_ENDPOINTS: "{{ .Values.etcd.endpoints | join "," }}"

  TELEMETRY_ENDPOINT: "{{ .Values.internalServices.telemetryEndpoint }}"
  LOG_ENDPOINT: "{{ .Values.internalServices.logEndpoint }}"

  {{- range $key, $value := .Values.config.custom }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
