apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Values.namespace }}
data:

  # Application configuration
  LOG_LEVEL: "{{ .Values.config.logLevel }}"

  # Database configuration
  DATABASE_POSTGRES_1: "{{ .Values.database.postgres_1 }}"

  # etcd configuration
  ETCD_ENDPOINTS: "{{ .Values.etcd.endpoints | join "," }}"

  TELEMETRY_ENDPOINT: "{{ .Values.internalServices.telemetryEndpoint }}"
  LOG_ENDPOINT: "{{ .Values.internalServices.logEndpoint }}"

  {{- range $key, $value := .Values.config.custom }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
