apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-ingestion-service.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-ingestion-service.labels" . | nindent 4 }}
data:

  # Monitoring configuration
  LOG_LEVEL: "{{ .Values.config.logLevel }}"
  TELEMETRY_ENDPOINT: "{{ .Values.config.internalServices.telemetryEndpoint }}"

  # Database configuration
  DATABASE_POSTGRES_1: "{{ .Values.config.database.postgres_1 }}"

  # etcd configuration
  ETCD_ENDPOINTS: "{{ .Values.config.etcd.endpoints | join "," }}"


  {{- range $key, $value := .Values.config.custom }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
