apiVersion: v2
name: tradefence-ws-gateway
description: WebSocket Gateway for TradeFence
sources:
  - git+ssh://git@git.tradefence.in:ws-gateway.git
maintainers:
  - name: Amal C.S
    email: amal4cs@gmail.com
type: application
version: 1.0.0
appVersion: "1.0.0.alpha.2"
