apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-repository.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-repository.labels" . | nindent 4 }}
data:

  # Redis configuration
  {{- if .Values.config.redis.enabled }}
  REDIS_HOST: "{{ .Values.config.redis.host }}"
  REDIS_PORT: "{{ .Values.config.redis.port }}"
  REDIS_DB: "{{ .Values.config.redis.db }}"
  REDIS_MAX_CONNECTIONS: "{{ .Values.config.redis.maxConnections }}"
  REDIS_TIMEOUT: "{{ .Values.config.redis.timeout }}"
  {{- end }}

  # Application configuration
  LOG_LEVEL: "{{ .Values.config.logLevel }}"

  DATABASE_POSTGRES_1: "{{ .Values.config.database.postgres_1 }}"

  {{- range $key, $value := .Values.config.custom }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
