apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Values.namespace }}
data:

  # Redis configuration
  {{- if .Values.redis.enabled }}
  REDIS_HOST: "{{ .Values.redis.host }}"
  REDIS_PORT: "{{ .Values.redis.port }}"
  REDIS_DB: "{{ .Values.redis.db }}"
  REDIS_MAX_CONNECTIONS: "{{ .Values.redis.maxConnections }}"
  REDIS_TIMEOUT: "{{ .Values.redis.timeout }}"
  {{- end }}

  # Application configuration
  LOG_LEVEL: "{{ .Values.config.logLevel }}"

  DATABASE_POSTGRES_1: "{{ .Values.database.postgres_1 }}"

  {{- range $key, $value := .Values.config.custom }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
