apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
  annotations: {}
spec:
  type: {{ .Values.service.type }}
  # Session affinity for WebSocket connections
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.grpcPort }}
      protocol: TCP
      name: grpc
    - port: {{ .Values.healthPort }}
      targetPort: {{ .Values.healthPort }}
      protocol: TCP
      name: health
  selector:
    app: {{ .Values.appName }}
