apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "data-repository.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-repository.labels" . | nindent 4 }}
