apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Values.namespace }}
data:

  # Application configuration
  LOG_LEVEL: "{{ .Values.config.logLevel }}"

  # User Data Repository configuration
  USER_DATA_REPOSITORY_ADDR: "{{ .Values.internalServices.userDataRepository.address }}"

  {{- range $key, $value := .Values.config.custom }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
