apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-service.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:

  # Application configuration
  LOG_LEVEL: "{{ .Values.config.logLevel }}"

  TELEMETRY_ENDPOINT: "{{ .Values.config.internalServices.telemetryEndpoint }}"

  # User Data Repository configuration
  USER_DATA_REPOSITORY_ADDR: "{{ .Values.config.internalServices.userDataRepository.address }}"

  {{- range $key, $value := .Values.config.custom }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
