apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
  annotations: {}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $name, $config := .Values.service.ports }}
    - port: {{ $config.port }}
      targetPort: {{ $config.targetPort }}
      protocol: {{ $config.protocol }}
      name: {{ $name }}
    {{- end }}
  selector:
    {{- include "user-service.selectorLabels" . | nindent 4 }}
