apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "trigger-scheduler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trigger-scheduler.labels" . | nindent 4 }}
