apiVersion: v2
name: tradefence-user-service
description: User service for TradeFence platform
sources:
  - git+ssh://git@git.tradefence.in:user-service.git
maintainers:
  - name: Amal C.S
    email: amal4cs@gmail.com
type: application
version: 1.0.0
appVersion: "1.0.1-hotfix-build.20260126-0220.6f9bdfa"
