apiVersion: v2
name: tradefence-user-service
description: User service for TradeFence platform
sources:
  - git+ssh://git@git.tradefence.in:user-service.git
maintainers:
  - name: Amal C.S
    email: amal4cs@gmail.com
type: application
version: 1.0.0
appVersion: "manual-tag-v1"
