apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    app: {{ .Values.appName }}
  publishNotReadyAddresses: {{ .Values.service.publishNotReadyAddresses }}
  ports:
  - name: etcd-client
    port: {{ .Values.ports.client }}
    targetPort: etcd-client
    protocol: TCP
  - name: etcd-server
    port: {{ .Values.ports.server }}
    targetPort: etcd-server
    protocol: TCP
  - name: etcd-metrics
    port: {{ .Values.ports.metrics }}
    targetPort: etcd-metrics
    protocol: TCP
