# Dev configuration for User Data Repository

appName: data-repository
namespace: app
environment: dev

# Application configuration
config:
  logLevel: "DEBUG"
  custom: {}

database:
  postgres_1: "postgres://devuser:devpass@dev.tradefence.in:5432/tradefence?sslmode=disable"
