tempo:
  enabled: true
  serviceName: grafana-tempo
  persistence:
    enabled: false
    size: 5Gi
  tempoQuery:
    enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
